configs:
- id: itsm
  config:
    name: dt_ITSM
    template: ITSM.json
    skip: false
  type:
    settings:
      schema: builtin:tags.auto-tagging
      scope: environment
- id: slo
  config:
    name: dt_SLO
    template: SLO.json
    skip: false
  type:
    settings:
      schema: builtin:tags.auto-tagging
      scope: environment
